[build]
  command = "npm run build"
  publish = "build"

[dev]
 command = "npm run dev"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
